### ISSUE TITLE
Feature request: Restore defaults

### ISSUE THREAD

**Issue by ChaseGrant** [bp2008/BetterClearTypeTuner#1]
It would be really awesome if the program had an option to restore the default settings in case you didn't like the changes at all.

**Comment by bp2008** [comment]
There already is a Restore Defaults button, but at your prompting I have looked more deeply into what the defaults actually are supposed to be, and it looks like the button is a little bit wrong in this release.  It sets the contrast to `1200`, but true default on a clean win10 system is `0` which is actually out of the valid range of inputs.  Microsoft's documentation suggests the default is `1900` but I've never seen that in reality.

![screenshot](https://i.imgur.com/hKllsmx.jpg)

ANYWAY, the next release of this tool should have updated default behavior, and I'll move the Restore Defaults button up to make it harder to miss.  In the meantime, to get "true defaults", you can do it through the registry editor.

In `HKEY_CURRENT_USER\Control Panel\Desktop`, set:
`FontSmoothing` = `2`  
`FontSmoothingGamma` = `0`  
`FontSmoothingOrientation` = `1`  
`FontSmoothingType` = `2`

Delete all of the subfolders in `HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics` (subfolders are typically named `DISPLAY1`, `DISPLAY2`, etc)

If `HKEY_LOCAL_MACHINE\Software\Microsoft\Avalon.Graphics` exists, delete all of its subfolders just the same as before.

Following those steps and rebooting will get the system back to how a fresh windows install normally is.

**Comment by bp2008** [comment]
Alright, the Restore Defaults button has been improved and moved up in Version 1.2, just released.

**Comment by ChaseGrant** [comment]
Thank you
