### ISSUE TITLE
Doesn't Account for All Registry Settings

### ISSUE THREAD

**Issue by skycyclepilot** [bp2008/BetterClearTypeTuner#12]
Under this key...

Computer\HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics\

There are six variables for each monitor - ClearTypeLevel, EnhancedContrastLevel, GammaLevel, GrayscaleEnhancedContrastLevel, PixelStructure, and TextContrastLevel.  Not all these variables are accounted for, or adjustable, in BetterClearType Tuner.  A new version that accounts for all these settings would be nice.

**Comment by bp2008** [comment]
Sorry, I don't know what those do (if anything), and I don't have time or interest to figure it out.

**Comment by skycyclepilot** [comment]
> Sorry, I don't know what those do (if anything), and I don't have time or interest to figure it out.
I understand.  I know it's time consuming.  The extra settings have something to do with darkening and widening the fill-in that ClearType does, while controlling the amount of fringing.  ClearType Tuner is more versatile and yields better results, but requires quite a bit of experimentation to understand what it's doing.
