### ISSUE TITLE
Settings per monitor

### ISSUE THREAD

**Issue by thany** [bp2008/BetterClearTypeTuner#15]
Windows can do this. BCT doesn't seem to have any knowledge of multiple monitor setups. So can this please become supported in some way?

For the moment, it might be important to know which monitor(s) it is setting cleartype preferences for.

**Comment by bp2008** [comment]
Yup, that was mentioned in the readme.  I absolutely agree it would be good if per-monitor settings worked.  But they don't so I didn't include anything for it here.

**Comment by thany** [comment]
So for which monitors _does_ it tune? Or does it tune for all monitors at once?

**Comment by bp2008** [comment]
This app sets registry keys associated with all connected monitors at once.  These are at `HKLM\Software\Microsoft\Avalon.Graphics\{monitorName}` and `HKCU\Software\Microsoft\Avalon.Graphics\{monitorName}`.  You can look at them in regedit if you like, and change them however you like, reboot, and see for yourself that multi monitor text rendering settings are non-functional.

These registry keys are only assigned for backwards compatibility.  The thing that actually seems to change text rendering behavior is calling windows API functions that do not have a way to specify a particular monitor.
