### ISSUE TITLE
Windows Defender detects Trojan:Script/Wacatac.H!ml in the downloaded zip file. 

### ISSUE THREAD

**Issue by toshiroakari** [bp2008/BetterClearTypeTuner#17]
The downloaded zip file is triggering windows defender. 

BetterClearTypeTuner.1.4.0.1.zip

Trojan:Script/Wacatac.H!ml

**Comment by bp2008** [comment]
Hard to say why it would do that.  Doesn't happen on any system I tested it on and the virustotal report is totally clean.

**Comment by aisareru** [comment]
This is really weird. I tired downloading it today and there was no trigger. I did restart my system so I don't know if that's what fixed it. Anyway, it's running fine now. Looks like it was a false positive. Thankyou.

**Comment by korbosoft** [comment]
Windows Defender try not to act schizophrenic challenge (impossible)
