### ISSUE TITLE
Is this how it's supposed to be? - blue and yellow colored words

### ISSUE THREAD

**Issue by Whitesttax** [bp2008/BetterClearTypeTuner#19]
Hey there! I was hoping you could help me out, I just got my new TV, QN90B, which uses BGR. 
I'm trying to make BetterClearType work but I'm not sure exactly how to.
Here's my problems: 

First, if I move the window around on my screen, the blue and yellow color from words move around (I'm not sure why the colors are there)
Same settings, only moved the window around a bit:
![1](https://user-images.githubusercontent.com/20992483/216729573-cfff815a-87a6-4558-b5a2-001ff433f825.jpg)
![2](https://user-images.githubusercontent.com/20992483/216729578-3701582f-b330-42c9-8dfc-550ca9002478.jpg)

Now, if I disable AA: 
![3](https://user-images.githubusercontent.com/20992483/216729636-40356c52-3c4f-4dae-ab4e-224fb5ed8ca2.jpg)

Lastly, here's how max contrast vs no contrast look like:
![4](https://user-images.githubusercontent.com/20992483/216729734-e10c07df-4ccb-4c0c-9649-09aa5dccf1ba.jpg)
![5](https://user-images.githubusercontent.com/20992483/216729736-d033a13a-a88c-4a1c-8c1d-03094b6895c4.jpg)

**Comment by bp2008** [comment]
Hi.

>First, if I move the window around on my screen, the blue and yellow color from words move around

I don't know what you're talking about.  In your pictures, the zoomed text sample is showing BGR-antialiased text exactly how I would expect and I do not see a difference in how it is behaving between the first two pictures.

> (I'm not sure why the colors are there)

The colored edges are there because when it is done properly it can make the text appear smoother.

> Lastly, here's how max contrast vs no contrast look like:

That also looks like it is performing properly.  If the color fringing is too noticeable at higher contrast, you can reduce it and the intensity of the color will be reduced. 
 Personally I prefer the default value.

**Comment by Whitesttax** [comment]
Hey, thanks for the answer.
All of my pictures are based on the small text under Restore Defaults.

So for the first two pictures what I did was drag the app and move it around the screen, let's say from the right side of the screen to the left. By doing that it changes which words get colored. That's what I was trying to show.

I didn't know the coloring was intended. Not sure if my pictures capture it well enough but it's quite strong, having lots of blue and yellow words, depending on the position on the screen as stated, feels a bit weird. But I do understand the idea now.

Max contrast seems to give me the least colors in the words.

**Comment by bp2008** [comment]
Is your desktop at 100% DPI scale?  Maybe the DPI scaling isn't working right in the app.

Unfortunately digital pictures of digital displays suffer from a lot of artifacts whenever the pixel size of the display is too closely aligned to the pixel size of the camera.  So while I do see color fringing around the small text in your pictures, it is certainly not the same as what you see in person.

Just pick whatever you like best for contrast, and feel free to try the program called [mactype](https://www.mactype.net/) if you want more control over text rendering.

**Comment by Whitesttax** [comment]
No it's not 100%, it's a 43" so I use it at 150 or 200 something like that. I'll try both yours again with 100 and that one tomorrow now that I understand a bit better what is going on.
Overall, webpages on Firefox look great even with Windows clear type, just like a proper monitor. But for a few things like a folder with files in it, the file names look a bit weird like a couple words were painted blue or yellow. I wonder why that happens, when on Firefox text looks perfect gray and is also as legible as it can get. I did read that different programs work differently but Windows, in this case using its own clear type, not being able to show clear gray/white colors in desktop, isn't it a bit weird?

**Comment by bp2008** [comment]
Make sure your TV isn't doing any kind of overscan or underscan.  It would cause the antialiased text to be misaligned with the physical subpixels which would cause all kinds of color fringing.

**Comment by Whitesttax** [comment]
Hey there, just to let you know that I fixed it! Turns out my laptop which has intel integrated graphics was outputing in the wrong color mode, 420. I changed it to RGB/444 and it looks perfect now!! Not a single color on my texts anymore :D

**Comment by bp2008** [comment]
Oh wow, good catch.  I did not think of that but it sure would have that effect.
