### ISSUE TITLE
Allow manual selection of font in program

### ISSUE THREAD

**Issue by improwise** [bp2008/BetterClearTypeTuner#2]
One nice addition to this would be if we could manually choose what font is used in the program for samples. It seems like it is the system font that is used, which does not work that well if you have manually  changed that to one that does not use ClearType, but still other problems keep on using ClearType and/or other fonts (like Firefox). Thanks.

**Comment by improwise** [comment]
After I had changed the default system font (using registry hacks) I could no longer see any difference between the alternatives in the preview window. My guess that has to do with the fact that I have replaces Segoe UI with MS Sans Serif (which is not a ClearType font) and that the same font was then used in the preview window and causing this.

**Comment by bp2008** [comment]
I've added a button to the upper right corner where you can change the font.

https://github.com/bp2008/BetterClearTypeTuner/releases

**Comment by improwise** [comment]
Great, thanks for this and for a great application.
