### ISSUE TITLE
DPI Awareness

### ISSUE THREAD

**Issue by berlihingen** [bp2008/BetterClearTypeTuner#3]
DPI Awareness would be extremely helpful. Or at least a resizable app window. Tried to fix it through win10 compatibility settings, but "Override scaling by System" does nothing, then "by Application" works well but fixed app size doesn't allow to view/use all the settings.

**Comment by bp2008** [comment]
On my system, the default DPI scaling settings have this app use bitmap scaling which retains the intended layout correctly.

You should get the same if you use these compatibility settings: 
![image](https://user-images.githubusercontent.com/5639911/86487194-b57eb200-bd1a-11ea-93a8-2a5a2342901a.png)

Unfortunately I built the app using Windows Forms which has TERRIBLE dpi scaling capabilities.  I just spent some time trying to enable DPI scaling awareness in the app but it didn't work out.  Windows scales the fonts incorrectly so I can only make the app look right at one DPI scale.  The app would have to be rebuilt with a WPF GUI unfortunately, to fix this.
