### ISSUE TITLE
EnhancedContrastLevel

### ISSUE THREAD

**Issue by basaran** [bp2008/BetterClearTypeTuner#4]
Hi,

EnhancedContrastLevel seems to be functional. I was messing around cleartype registry manually to improve the rendering of vscode. After changing to 0, this is what I got:

before
![image](https://user-images.githubusercontent.com/30809170/86440401-5bf59380-bcd8-11ea-984c-e95b51a992d4.png)

after
![image](https://user-images.githubusercontent.com/30809170/86440419-64e66500-bcd8-11ea-8f43-45afff7d2468.png)

Thank you for trying to make windows a better world.

**Comment by basaran** [comment]
apparently, I lost myself during reboots, the font was changed. documentation is correct, that setting hadn't made a difference.

**Comment by bp2008** [comment]
Yeah, it looked like different fonts.  In particular the 'U' has a serif in one version.
