### ISSUE TITLE
Different font smoothing?

### ISSUE THREAD

**Issue by improwise** [bp2008/BetterClearTypeTuner#5]
I noticed that in BetterClearTypeTuner there is an option to enable/disable font smoothing and with it enabled, you can select between Greyscale, RGB and BGR. In a similar program called ClearTypeSwitch, you instead have the option to disable ClearType and also disable font smoothing, which also seem to match the built in options in Windows where you have a check box to disable ClearType and one to disable Font Smoothing (under performance options). 

This begs the question, what is the difference and what option in BetterClearType actually offers font smoothing without ClearType? Is that the same option as using Greyscale? Or is this option to only use "old school" font smoothing actually missing?

AFAIK, Greyscale is the same thing as ClearType disabled, if so, perhaps that should be made more obvious in the UI. 

http://karpolan.com/software/cleartype-switch/

Thanks.

**Comment by bp2008** [comment]
I believe "ClearType" specifically refers to subpixel antialiasing, which is RGB and BGR.  So yes, choosing Grayscale means you get font smoothing without ClearType.

What do you think would make it clearer?  Rename the "Grayscale" option to "Grayscale (ClearType off)" ?

I should probably rebuild this app using the WPF framework anyway so it works properly with DPI scaling.  I just don't use any high DPI monitors on my desktop currently so I don't care enough :)

**Comment by improwise** [comment]
Yes, I think a change like "Grayscale (ClearType off)" would make it more obvious for the causal user as there is a corresponding option in Windows on ClearType settings. 

But if you don't have high DPI screens, I guess you at least need this program to disable ClearType :)

**Comment by bp2008** [comment]
I tried rebuilding the GUI with WPF last week, but it did not work well.  The main issue was that updated settings wouldn't take effect properly on the app itself until you restarted it.  So I won't be releasing a WPF version.
