### ISSUE TITLE
Font selection in Win 8.1?

### ISSUE THREAD

**Issue by sunlightspectre** [bp2008/BetterClearTypeTuner#7]
See title; would it be possible to get a version of this that changes UI in Win 8.1? I have to use this computer for work, and - unfortunately - my feelings about Segoe UI match my opinions about cleartype. Well, either way, thanks for your work, it's a quick way to show people that no, my complaints are valid, yes, I've tried cleartype, and yes, every single potential value of it is awful, ahaha...

**Comment by bp2008** [comment]
That is a feature of version 1.3.  Does the change font button (upper-right corner) not work in Win 8.1?

I don't think I have any devices running 8.1, and only one running 8.0.

**Comment by sunlightspectre** [comment]
How peculiar; I'll walk through what I'm doing, in case some obvious user error is the culprit.

* BCTT is run as admin. For completeness' sake, I also tried these steps in safe mode.
* Font anti-aliasing is disabled.
* Change font, in the upper right, is selected. I tested the following with Arial, Carme, and Times New Roman.
* All fonts display correctly in the preview pain.
* On close, the changes do not take effect, even following a full reboot.

Let me know if you see anything off in my approach, here. Thank you for the assist!

**Comment by bp2008** [comment]
Oh, I see.  That is working as intended.  That isn't meant to change your system fonts, only the fonts used within the BetterClearTypeTuner program so you can see the effect of cleartype settings on different fonts.

**Comment by sunlightspectre** [comment]
Hah, fair enough. I'd hoped to find a convenient way to swap system fonts on the fly - given how cumbersome doing it in Win7 was, and that it doesn't seem to work the same in Win 8(.1), so it goes.

Thanks for the replies, I'll just close this down, then..!
